### ISSUE TITLE
version tagging should follow a policy

### ISSUE THREAD

**Issue by jku** [actions/dependency-review-action#102]
Tagging policy commonly used by GitHub for actions is "not great but not terrible": typically the repositories tag releases with specific tags (like "v1.0.2") and then also have a major version tag (like "v1") that is usually moved to match the latest specific release tag. This enables using `@v1` in workflow files.

This repository has a v1 tag leading users to think that they can use the same strategy here. Unfortunately that tag points to the initial commit and not the latest release (at the moment of writing "v1.0.2"). So if someone has `uses: actions/dependency-review-action@v1` they are using the initial commit of this repository. This seems like the worst option: either the tag should not exist or it should get moved on every release.

**Comment by jku** [comment]
> uses: actions/dependency-review-action@v1

This is what the README suggests so it seems likely that most users of this action are using the initial commit.

**Comment by jku** [comment]
right now they match. Two hours ago, they did not. I was looking at the web UI when filing this but e.g. https://github.com/theupdateframework/python-tuf/runs/6401971278?check_suite_focus=true is an example run from a few weeks ago that used `v1` and ended up using the initial commit.

**Comment by jku** [comment]
Here is an example from two hours ago that used v1 and ended up running the initial commit: https://github.com/vmware-tanzu/community-edition/runs/6753289582?check_suite_focus=true

So it looks to me like someone just fixed the tag silently today

**Comment by febuiles** [comment]
@jku Thanks for the links! We had an old branch called `v1` which I removed while investigating the tags you mentioned, I'm guessing it was picking up the branch instead of the tag name. I'm closing this issue, but please re-open it if you have more comments or if it pops up again.
