### ISSUE TITLE
Error: Dependency review is not supported on this repository. Please ensure that Dependency graph is enabled, see https://github.com/xxxx/xxxxx/settings/security_analysis

### ISSUE THREAD

**Issue by palanisamy-emis** [actions/dependency-review-action#109]
Hi Guys,
Dependency graph is enabled in our repo. But still it shows an error in Github actions. 

My build.yaml looks like,
        - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1

<img width="1331" alt="Screenshot 2022-06-13 at 2 17 27 PM" src="https://user-images.githubusercontent.com/70691178/173315826-6f347a8e-f861-46bb-a9a9-0971d43737dc.png">

<img width="1034" alt="Screenshot 2022-06-13 at 2 29 08 PM" src="https://user-images.githubusercontent.com/70691178/173318143-e637fa1e-16e9-4531-98e3-276a64958aa2.png">

Could someone help me to fix this issue?

**Comment by febuiles** [comment]
@palanisamy-emis Sorry for the issues! I can see this is a private repo, couple of questions:

1. Can you try to use version `1.0.2` and let us know if the output is any different?
2. Is your organization a GitHub Advanced Security customer? This is required to enable the Dependency Review Action in private repos.

**Comment by febuiles** [comment]
Please re-open if you happen to be on an enterprise plan with GitHub Advanced Security enabled.
