### ISSUE TITLE
dependency-review-action cannot find a license for dependency-review-action

### ISSUE THREAD

**Issue by ericcornelissen** [actions/dependency-review-action#182]
On the first run this Action did in one of my repositories (first time using it) I looked at the output and noticed a curious log ([full logs here](https://github.com/ericcornelissen/git-tag-annotation-action/runs/7679515582)):

```log
We could not detect a license for the following dependencies:
.github/workflows/deps-analysis.yml » actions/dependency-review-action@2.0.4
```

From what I can tell, this repositories' license is present and well-formed (there's a [LICENSE](https://github.com/actions/dependency-review-action/blob/415088b56ea73ed3d24525747212dc04fbb7d9b9/LICENSE) file, as well as [the `"license"` entry in `package.json`](https://github.com/actions/dependency-review-action/blob/415088b56ea73ed3d24525747212dc04fbb7d9b9/package.json#L26), and GitHub displays the correct license in the UI).

I'm not sure what exactly the problem is, but I would not expect this Action to log a "problem" with itself.

**Comment by RobPasMue** [comment]
Also experiencing this issue in some of my repos... looking forward to its resolution! =)

**Comment by jcasner** [comment]
I'm finding this issue in testing this action, also. I tried importing a package with a proper `license` entry in it's package.json as well as a LICENSE file but am getting this message and not seeing the expected failure from the action.

**Comment by febuiles** [comment]
@jcasner Thanks for diving into this, to add further details: The API only returns licenses for the top _N_ licenses for any given repo (not sure if _N_ is the same for all ecosystems). I'm thinking that the best way to proceed here is to call the GitHub licenses API endpoint if `license :null` in the vulnerabilities payload, what do you think?

**Comment by febuiles** [comment]
License detection was improved in the latest release of the Action by adding a fallback to GitHub's License API. Please re-open this issue if you're still experiencing problems.

**Comment by raphaeldeem-jsq** [comment]
I am encountering this issue, is there a workaround to prevent the tool from flagging itself? Thanks!
