### ISSUE TITLE
Getting 'review is not supported on this repository' error on private repo under free plan

### ISSUE THREAD

**Issue by micalevisk** [actions/dependency-review-action#19]
I'm getting the following error:

```
Error: Dependency review is not supported on this repository. Please ensure that Dependency graph is enabled, see https://github.com/codemeistre/backend/settings/security_analysis
```

even tho we do I have _Dependency graph_ enabled in the repository:

![image](https://user-images.githubusercontent.com/13461315/162049026-11eee7c1-3954-4fd6-8a44-8cb5df47f6f2.png)

On private repositories (under free plan), should we do something besides the usual setup? :thinking: Thanks in advance.

**Comment by courtneycl** [comment]
Hi @micalevisk -- thanks for your interest in the action. It's available for private repos if the repo has GitHub Advanced Security licensed; it's not offered under the free plan (though it's available for all public repositories). We'll make that error message more specific to prevent future confusion.

**Comment by MatthewRyanRead** [comment]
I suggest reopening this until there is a better message in place!

**Comment by micalevisk** [comment]
@courtneycl I guess you guys can lock this Issue and close it when the message becomes more clear or something like that.

**Comment by courtneycl** [comment]
Good idea - thanks.

**Comment by febuiles** [comment]
Hey folks. We've updated our error messages and added a [small note to our README](https://github.com/actions/dependency-review-action/pull/65/files). Closing this, feel free to reopen if y'all find it to still be unclear.

**Comment by courtneycl** [comment]
@rvalitov customers on the Team plan will soon be able to purchase Secret Protection separately: https://github.blog/changelog/2025-03-04-introducing-github-secret-protection-and-github-code-security/

**Comment by codyn-txst** [comment]
> Hey folks. We've updated our error messages and added a [small note to our README](https://github.com/actions/dependency-review-action/pull/65/files). Closing this, feel free to reopen if y'all find it to still be unclear.

[I have a related question](https://github.com/actions/dependency-review-action/pull/65/changes#r3319723091). Is it Code Security specifically under Advanced Security that's needed in order to allow this action to run for private repos?

**Comment by ahpook** [comment]
> Is it Code Security specifically under Advanced Security that's needed in order to allow this action to run for private repos?

That's correct
