### ISSUE TITLE
Unknown Licenses

### ISSUE THREAD

**Issue by hfhbd** [actions/dependency-review-action#201]
The output of this [action](https://github.com/actions/dependency-review-action) prints `actions/dependency-review-action has an unknown license`.

https://github.com/hfhbd/routing-compose/actions/runs/2891020667/attempts/2#summary-7922844964

**Comment by ericcornelissen** [comment]
Duplicate of #182

**Comment by hfhbd** [comment]
Thanks

**Comment by FYI5050997** [comment]
> The output of this [action](https://github.com/actions/dependency-review-action) prints `actions/dependency-review-action has an unknown license`.
> 
> const { Buffer } = require('node:buffer');

// Need to keep around a few small chunks of memory.
const store = [];

socket.on('readable', () => {
  let data;
  while (null !== (data = readable.read())) {
    // Allocate for retained data.
    const sb = Buffer.allocUnsafeSlow(10);

    // Copy the data into the new allocation.
    data.copy(sb, 0, 0, 10);

    store.push(sb);
  }
})
