### ISSUE TITLE
License detection doesn't work with python requirements.txt or dev_requirements.txt 

### ISSUE THREAD

**Issue by levyitay** [actions/dependency-review-action#242]
I have been testing `dependency-review-action` on a public repo with only python `requirements.txt` and `dev_requirements.txt`
The action does detect vulnerabilities but could not find any of the licenses. 

Is there something special that is needed to be done for it work?

**Comment by febuiles** [comment]
Hi @levyitay. Can you provide an example repo where we could reproduce this?

**Comment by levyitay** [comment]
@febuiles take a look at: https://github.com/levyitay/gh_public_test
I traced the problem back to the API itself see here: https://github.com/orgs/community/discussions/33527

**Comment by febuiles** [comment]
@levyitay thanks a ton for the report and the test repo. I'm leaving this issue open until the API licenses are fixed.

**Comment by febuiles** [comment]
@levyitay we've improved license detection in the latest release of the Action and you should now be seeing licenses for the Python dependencies. Please re-open if that's not the case.
