### ISSUE TITLE
Detecting vulnerability for a dependency that is supposed to be fine 

### ISSUE THREAD

**Issue by israelboudoux** [actions/dependency-review-action#247]
Hi guys,

My team is using Dependency Review in our pipeline and we are receiving an error for a vulnerability that is not supposed to exist for the dependency in case: **color 1.4.0**

Here it is the link to the failed item:
https://github.com/EYBlockchain/nightfall_3/actions/runs/3088956171/jobs/4996018312

According to the docs (https://github.com/advisories/GHSA-gh88-3pxp-6fm8) only versions **>= 1.4.1** for **colors** are affected. 

I guess that might be an issue in Dep. Rev. Action.

Please, let me know your thoughts. 

Thanks in advance!

**Comment by febuiles** [comment]
@israelboudoux Hello and thanks for reporting this issue! This is an issue with the Dependency Review API, and it's currently being tracked in https://github.com/actions/dependency-review-action/issues/150. Closing this issue as a duplicate.
