### ISSUE TITLE
Supporting action output

### ISSUE THREAD

**Issue by davidmally-at** [actions/dependency-review-action#250]
👋 Hi! My team has been using this action, and we were wondering if it's possible to get the summary output from the action to use in subsequent workflow steps. A fake example:
![image](https://user-images.githubusercontent.com/61764280/191811701-7209e891-b0fd-4827-8e5b-616977c03e08.png)

We'd like to have this summary output available as output from the action itself, so that we can do things like post it as a comment on the PR that corresponds to the workflow run, notify people in Slack, etc. Is that supported today and I'm just missing it? If not, I would be happy to put together a pull request to support this.

**Comment by febuiles** [comment]
Hi @davidmally-at! I don't think we have anything in place to support the use case you're proposing, a PR would be extremely welcome! 🙇

**Comment by YSCG1130** [comment]
J

**Comment by uli-f** [comment]
I'd also support this feature request.

The summary used for a PR comment is compiled. All that is left to do is output that from the workflow so that it could be picked up by later steps.

**Comment by jsoref** [comment]
If that's all that's desired, then it'd be a pretty easy thing to do right here:
https://github.com/actions/dependency-review-action/blob/80f10bf419f34980065523f5efca7ebed17576aa/src/comment-pr.ts#L16-L23

**Comment by febuiles** [comment]
This functionality is now available in the latest release of the Action (4.1.2) thanks to @jsoref. You can find an [example here](https://github.com/actions/dependency-review-action/blob/main/docs/examples.md#getting-the-results-of-the-action-in-a-later-step) of how to use the output. Closing this issue.
