### ISSUE TITLE
support event types other than `pull_request`

### ISSUE THREAD

**Issue by PatMyron** [actions/dependency-review-action#30]
`This run was triggered by the "push" event, which is unsupported. Please ensure you are using the "pull_request" event for this workflow.`

https://github.com/actions/dependency-review-action/blob/0e686847c07129d741636f8826e19766b940064b/src/main.ts#L12

**Comment by PatMyron** [comment]
For more context, we have hundreds of repos using one reusable workflow where we add actions centrally like this, and it's triggered by more event types like `push`, `schedule`, `workflow_dispatch`, etc

**Comment by Aaronkala** [comment]
We would love to have this also. We we're trying to enable the [github merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues) but due to the actions running on `push` this wasn't possible.

The options we currently have are:
- Stop requiring the dependency-review action as a "needed check"
- Don't use merge queue

**Comment by PatMyron** [comment]
working around with `if: github.event_name == 'pull_request'` found in https://github.com/fastify/fastify/pull/3884#discussion_r866687840

**Comment by febuiles** [comment]
@PatMyron @Aaronkala Thanks for the report! Do these other even types support these fields? https://github.com/actions/dependency-review-action/blob/0e686847c07129d741636f8826e19766b940064b/src/main.ts#L21-L24 

If that's the case I think we can update the code to include them. I'm planning to start with `workflow_dispatch`, what else would benefit from this?

**Comment by Aaronkala** [comment]
To me it looks like the `head_ref` and `base_ref` are only available on `pull_request` or `pull_request_target` events.

`repo` and `owner` should be available in all

From the docs: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

**Comment by febuiles** [comment]
Thanks for the insight @Aaronkala! Maybe it'd make sense to add extra optional parameters to the Action so it accepts head/base revisions. Leaving this open while considering other options (PRs to mitigate this issue in the meantime are welcome!)

**Comment by Serpentiel** [comment]
hey 👋, just ran into this issue too, and `pull_request_target` is exactly what I'm looking for :)

**Comment by febuiles** [comment]
Thanks to the amazing work by @WillDaSilva the Action should [now support event types different to "pull_request"](https://github.com/actions/dependency-review-action/pull/165). You can test this by using the `optional-refs` branch of this repo:

```yml
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@optional-refs
        with:
          base-ref: ...
          head-ref: ...
```

More info about defaults, and how to pass refs to other types of events in: https://github.com/actions/dependency-review-action/tree/optional-refs#configuration. 

If no issues are found I'll cut a new release before the end of the week.

**Comment by febuiles** [comment]
Actually both PRs already contain documentation, [2.1.0](https://github.com/actions/dependency-review-action/releases/tag/v2.1.0) has been released with support for other event types! 

If you see something behaving funny please open a new issue.
