### ISSUE TITLE
Need way to whitelist specific dependencies or invalid licenses

### ISSUE THREAD

**Issue by jentfoo** [actions/dependency-review-action#385]
We are running into an issue with libraries which don't define their license in a format that dependency-review can accept.  For example:
https://github.com/BurntSushi/same-file/blob/5799cd323b8eefd17a089c950dac113f66c89c9e/Cargo.toml#L13
https://github.com/BurntSushi/aho-corasick/blob/979cf735e267c361806dd34224699430531626ab/Cargo.toml#L10
https://github.com/rayon-rs/rayon/blob/7413495e3307f7fbf945b7742f9fce9b1aa2ff58/Cargo.toml#L9

Several of these have been been updated with PR's to help address the issue within the projects.  But this is not a sustainable process and it is severely inhibiting the ability to use dependency review.

We need an ability to define exceptions for these specific (but invalid) license formats or these specific dependencies.

I see this previous PR: https://github.com/actions/dependency-review-action/issues/133

However it looks to have only addressed whitelisting CVE's, and not an ability to whitelist dependencies.

Thank you!

**Comment by febuiles** [comment]
@jentfoo We don't have cycles to work on this right now, but if it's something you need I'd be happy to help guide a PR to add the new option. 

To add  `allow_dependencies` (maybe a `denylist` too?) to the config file we'd need each dependency with their ecosystem

```
allow_dependencies:
  npm: "dep1, dep2, dep3"
```

Adding a new filter in [filters.ts](https://github.com/actions/dependency-review-action/blob/main/src/filter.ts) to handle the allowlist of deps and calling that in our ugly [main.ts filters section](https://github.com/actions/dependency-review-action/blob/main/src/main.ts#L32-L38) should do the job.

**Comment by jentfoo** [comment]
Closing issue since this feature appears to have been added.  I was recently able to utilize `allow-dependencies-licenses` to configure specific dependencies to ignore with invalid license specifications.
