### ISSUE TITLE
Not scanning package.json in the subdirectories of the project

### ISSUE THREAD

**Issue by l009560-CA** [actions/dependency-review-action#386]
Looks like this action only scans package.json in the root folder. There are may projects which have package.json in the subdirectories and it looks like that they are not scanned.

**Comment by febuiles** [comment]
Hi! Can you reproduce this in a public repo and paste a link to the run where the manifests are not properly detected? 

Are the non-root folder showing up in the Dependency Graph page? `https://github.com/<user>/<repo>/network/dependencies`?

**Comment by l009560-CA** [comment]
After looking the logs carefully and settings for the test repo, I need to close this issue as I can see that the action is scanning non-root manifest files.
