### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by jamime** [actions/dependency-review-action#392]
I am seeing the same error as #386 in that nested folders are not scanned.
The action exited with a success but no output.

```
2023-02-01T12:11:13.1721349Z ##[group]Run actions/dependency-review-action@v3
2023-02-01T12:11:13.1721586Z with:
2023-02-01T12:11:13.1721808Z   allow-licenses: MIT
2023-02-01T12:11:13.1722159Z   repo-token: ***
2023-02-01T12:11:13.1722367Z   fail-on-severity: low
2023-02-01T12:11:13.1722580Z   fail-on-scopes: runtime
2023-02-01T12:11:13.1722783Z ##[endgroup]
2023-02-01T12:11:36.2620407Z ##[debug]Node Action run completed with exit code 0
```
But as you can see there was no output.

I re-ran the job by closing and re-opening the PR and now I get a server error but with no information.
```
2023-02-01T12:19:44.9155116Z ##[group]Run actions/dependency-review-action@v3
2023-02-01T12:19:44.9155401Z with:
2023-02-01T12:19:44.9155651Z   allow-licenses: MIT
2023-02-01T12:19:44.9156004Z   repo-token: ***
2023-02-01T12:19:44.9156245Z   fail-on-severity: low
2023-02-01T12:19:44.9156492Z   fail-on-scopes: runtime
2023-02-01T12:19:44.9156725Z ##[endgroup]
2023-02-01T12:20:40.6476468Z ##[error]Server Error
2023-02-01T12:20:40.6521886Z ##[debug]Node Action run completed with exit code 1
```

I tried to reproduce this on a public repository but it works without a problem.

https://github.com/ChrisC-testorg/public-dependency-review/pull/1

Any ideas what could cause this, can we enable more logging to see what the server error is?

For context I'm trying to review all dependencies - so I'm copying the package files from different repositories. Is there another way to set the `basehead` to review all dependencies instead of just those that have changed - that would resolve this problem for me.

**Comment by jamime** [comment]
I raised a support ticket for this with information on how to reproduce the issue. Looks like the API is returning a 502.

#1993524

**Comment by fbjaras** [comment]
Any updates regarding this @jamime? We have the same (or at least a similar) issue with the action just failing with `Server Error` and no more info when running with debugging.

For context: we are moving around a lot of packages internally in a monorepo using yarn workspaces.

The actions seems really flaky and occasionally passes. but most of the time i get this error.

![Screenshot 2023-02-07 at 15 47 11](https://user-images.githubusercontent.com/111292329/217278100-b7b2df8f-44c8-49ec-b014-87eeb43a936e.png)

**Comment by febuiles** [comment]
@jamime @fbjaras are you able to use the [Dependency Review API](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28#get-a-diff-of-the-dependencies-between-commits) on the PRs where the Action fails? I'm guessing this is a server error, not something related to the Action, but it'd be good to have some confirmation before proceeding.

**Comment by fbjaras** [comment]
> @jamime @fbjaras are you able to use the [Dependency Review API](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28#get-a-diff-of-the-dependencies-between-commits) on the PRs where the Action fails? I'm guessing this is a server error, not something related to the Action, but it'd be good to have some confirmation before proceeding.

Yes this also fails. I guess i should raise a support ticket for this as well then!
Thank you!

**Comment by febuiles** [comment]
I've created a new issue to track this: https://github.com/actions/dependency-review-action/issues/398, closing this issue.

Contributions are always welcome. If you'd like to work on this enhancement please see our [contributor's guide](https://github.com/actions/dependency-review-action/blob/main/CONTRIBUTING.md), or ping me directly!

**Comment by dzmitry-lahoda** [comment]
I started to get same issue for some reason. I did nothing. No new deps or something. Just started to get error.

**Comment by febuiles** [comment]
@dzmitry-lahoda do you have a public repo where this behavior can be seen? Are you able to hit the [API directly](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28#get-a-diff-of-the-dependencies-between-commits)?

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/composable/pull/3790

https://github.com/ComposableFi/composable/actions/runs/5568024051/jobs/10172706662

![image](https://github.com/actions/dependency-review-action/assets/757125/dbac6a5a-5334-459e-a68d-f0ed552f2927)

It was success on 5 or 6 retry. 

Here is example debug enabled log 

[logs_76923.zip](https://github.com/actions/dependency-review-action/files/12067766/logs_76923.zip)

I think I saw issue when I deleted many files (like 100+, may be 1000). Like big diff fails deps bot.

**Comment by febuiles** [comment]
@dzmitry-lahoda thanks for the extra details. I can see that the timeout is coming from the GitHub API and not the Action itself:

```
$ gh api -H "Accept: application/vnd.github+json" repos/ComposableFI/composable/dependency-graph/compare/main...4c50abd
{
  "message": "Server Error"
}
gh: Server Error (HTTP 502)
```
