### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by grndvl1** [actions/dependency-review-action#41]
Running it on my private github and it fails with:

[dependency-review](https://github.com/grndvl1/BGB/runs/6201128754?check_suite_focus=true#logs)
failed 2 minutes ago in 3s
Run actions/dependency-review-action@v[1](https://github.com/grndvl1/BGB/runs/6201128754?check_suite_focus=true#step:3:1)
Error: Dependency review is not supported on this repository. Please ensure that Dependency graph is enabled, see https://github.com/grndvl1/BGB/settings/security_analysis

I have all the setting set to true

**Comment by courtneycl** [comment]
Hi @grndvl1 -- the action requires private repos to have a license for GitHub Advanced Security. We're improving the error message to be more specific for this case.

**Comment by grndvl1** [comment]
Maybe add that to the readme saying if you have a private repo and no AS then this script will not work.  This way others won't waste their time.
