### ISSUE TITLE
Support disabling check over `devDependencies`

### ISSUE THREAD

**Issue by Yash-Singh1** [actions/dependency-review-action#43]
There should be an option to disable `devDependencies` because some people just have testing frameworks and build tools in their `devDependencies`.

**Comment by Haku56** [comment]
I'd _notice_ some <del>mistakes</del>  and **make** some **marks** :heavy_check_mark:
A good job !

**Comment by joshjohanning** [comment]
@febuiles I believe the API supports it now? https://github.blog/changelog/2022-06-23-dependabot-alerts-filter-alerts-by-the-scope-of-the-dependency-runtime-and-development/

Will this be brought as an option to the action?

**Comment by febuiles** [comment]
Hi @joshjohanning -- Thanks for the heads up! I don't think the [Dependency Review API](https://docs.github.com/en/rest/dependency-graph/dependency-review) supports this yet, once it does I'll provide a new update!
