### ISSUE TITLE
Check dependency runtime/language requirements

### ISSUE THREAD

**Issue by romainmenke** [actions/dependency-review-action#445]
Dependencies that are distributed as source (most of them) will also have specific runtime or compiler version requirements.

Would it be within the scope of this package to also verify those?

-----

Example :

- my library aims to support Go 1.16 or later
- a dependency is introduced that depends on Go 1.20
- the action fails

Example :

- my library aims to support Go 1.16 or later
- a dependency is updated and now depends on Go 1.20
- the action fails

**Comment by febuiles** [comment]
@romainmenke do you have a more specific example using one of the currently using the [supported ecosystems](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems) by GitHub? I'm not sure if there's enough information in there and in the Dependency Review API to surface these sort of conflicts.

**Comment by romainmenke** [comment]
Ah, yes that is indeed not present in the API response : 

```
  {
    "change_type": "added",
    "manifest": "package-lock.json",
    "ecosystem": "npm",
    "name": "@csstools/postcss-hwb-function",
    "version": "2.2.0",
    "package_url": "pkg:npm/%40csstools/postcss-hwb-function@2.2.0",
    "license": null,
    "source_repository_url": "https://github.com/csstools/postcss-plugins",
    "scope": "runtime",
    "vulnerabilities": []
  },
```

I think it is more interesting for now to then have a dedicated check per ecosystem, outside of this action.

Thank you for the quick response!
