### ISSUE TITLE
A purl string argument is required.

### ISSUE THREAD

**Issue by tamacti-jun** [actions/dependency-review-action#493]
Hello @febuiles , @theztefan , @cnagadya, @sarahkemi 

![image](https://github.com/actions/dependency-review-action/assets/134579857/72d018a8-ace9-4dc5-82ef-96028fda5691)

hi, I'm getting this error, what should I do to solve the problem?

my file content is as follows.

![image](https://github.com/actions/dependency-review-action/assets/134579857/1a264310-7093-4f49-8c31-856fe986375d)

**Comment by tamacti-jun** [comment]
I don't understand what went wrong. my github repo is a public repo

![image](https://github.com/actions/dependency-review-action/assets/134579857/5f8fa6d2-7082-48e2-97cd-bf0e22962be4)
t

**Comment by febuiles** [comment]
@tamacti-jun Thanks for reporting the bug. We're working on a fix, in the meantime can I suggest you use `dependency-review-action@3.0.4` in your config file?

**Comment by febuiles** [comment]
@tamacti-jun This should be fixed in `v3` and `v3.0.6` of the Action, thanks for the report.

**Comment by tamacti-jun** [comment]
Thank you for your interest. have a nice work day
