### ISSUE TITLE
Dependency-review-action license checker not working

### ISSUE THREAD

**Issue by Mark-Miller-Kajabi** [actions/dependency-review-action#495]
https://github.com/actions/dependency-review-action/issues/182

I am having all licenses return as null in my checks for dependencies. Repositories have multiple licenses and some have known licenses, But every single one returned this as the response.

![image](https://github.com/actions/dependency-review-action/assets/99828500/18776f94-0b5c-4314-80f8-8aa28a55ddbf)

**Comment by febuiles** [comment]
@Mark-Miller-Kajabi can you share the YAML file or config options you're using to run the action?

**Comment by febuiles** [comment]
I hope to have a fix for this tomorrow, in the meantime please use `dependency-review-action@3.0.4` if this being too problematic.
