### ISSUE TITLE
`golang.org/x/` flagged with unknown license

### ISSUE THREAD

**Issue by lucacome** [actions/dependency-review-action#514]
It seems like all the `golang.org/x/` libraries are flagged with `Unknown License` even though they seem to use `BSD-3-Clause` license as you can see here for example https://cs.opensource.google/go/x/mod/+/master:LICENSE

Below the result of the scan

<h2>License Issues</h2>
<h4><em>go.mod</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>golang.org/x/mod</td><td>0.11.0</td><td>Null</td><td>Unknown License</td></tr><tr><td>golang.org/x/net</td><td>0.11.0</td><td>Null</td><td>Unknown License</td></tr><tr><td>golang.org/x/sys</td><td>0.9.0</td><td>Null</td><td>Unknown License</td></tr><tr><td>golang.org/x/term</td><td>0.9.0</td><td>Null</td><td>Unknown License</td></tr><tr><td>golang.org/x/text</td><td>0.10.0</td><td>Null</td><td>Unknown License</td></tr></table>
<blockquote><strong>Allowed Licenses</strong>: Apache-1.1, Apache-2.0, BSD-2-Clause, BSD-3-Clause, BSL-1.0, ISC, MIT, NCSA, OpenSSL, Python-2.0, X11</blockquote>

**Comment by febuiles** [comment]
@lucacome GitHub's Dependency Graph API returns license data that's based on what's available in https://clearlydefined.io, which does not support Golang. The Action will also use GitHub's Licenses API if the project is hosted here, but that's not the case with a lot of the Go ecosystem packages like the ones you listed above.

Until the Dependency Graph adds complete support for licenses in all ecosystems, we can't fix this behavior. Using the `allow-dependencies-licenses` option along with the problematic packages would get rid of the failures, but I understand this is a work-consuming, nasty hack :(
