### ISSUE TITLE
Using GitHub Actions dependencies in allow-dependencies-licenses

### ISSUE THREAD

**Issue by replicaJunction** [actions/dependency-review-action#530]
I'm adding this Action in a repo that needs to exclude GPL code as a general rule, but my organization has determined that it's okay to use GitHub Actions licensed under the GPL. I've got two specific actions that are still coming up as "license issues," despite adding them to the `allow-dependencies-licenses` key.

It's possible I've just got the wrong purl type for actions, but I haven't been able to find the correct value anywhere. The [Supported package ecosystems documentation](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems) for GitHub dependencies does not provide the explicit prefix name in the purl format required by the allow-dependencies-licenses config setting, and the [purl-spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst) does not list GitHub Actions as one of their commonly used types.

I've tried these types already:
* actions
* github
* yaml

Unfortunately, the repo is a private enterprise repo, and I can't provide a link to it here. However, here is a config file that reproduces this issue:

```yaml
comment-summary-in-pr: true
deny-licenses:
  - "GPL-2.0"
  - "GPL-3.0"
  - "LGPL-2.1"
allow-dependencies-licenses:
  - "pkg:github/SonarSource/sonarqube-quality-gate-action@1.1.0"
  - "pkg:github/SonarSource/sonarqube-scan-action@1.2.0"
```

This produces the following output in the comment:

---

<html>
<body>
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--borderColor-muted, var(--color-border-muted)); color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">License Issues</h2><h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 14px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><em style="box-sizing: border-box;">.github/workflows/code-quality.yml</em></h4>

Package | Version | License | Issue Type
-- | -- | -- | --
SonarSource/sonarqube-quality-gate-action | 1.1.0 | LGPL-3.0 | Incompatible License
SonarSource/sonarqube-scan-action | 1.2.0 | LGPL-3.0 | Incompatible License

<blockquote style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px 1em; color: var(--fgColor-muted, var(--color-fg-muted)); border-left: .25em solid var(--borderColor-default, var(--color-border-default)); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600); margin-top: 0px; margin-bottom: 0px;">Denied Licenses</strong>: GPL-2.0, GPL-3.0, LGPL-2.1</blockquote><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px 1em; color: var(--fgColor-muted, var(--color-fg-muted)); border-left: .25em solid var(--borderColor-default, var(--color-border-default)); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600); margin-top: 0px; margin-bottom: 0px;">Excluded from license check</strong>: pkg:SonarSource/sonarqube-quality-gate-action@1.1.0, pkg:SonarSource/sonarqube-scan-action@1.2.0</blockquote>
</body>
</html>

---

Here are my specific questions / issues:
* What is the correct purl type for GitHub Actions, as used by this action?
* How can I find details on these types in the future to troubleshoot issues like these?
* Could the action log the full purl strings for each dependency when it runs so users like me can see the full details behind why a package is or isn't considered excluded?
* If this is an error in this action and not in my config, can it be solved?

Thank you!

**Comment by febuiles** [comment]
> What is the correct purl type for GitHub Actions, as used by this action?

It should be `githubactions`. This is a provisional type that might change in the future, it's not listed in the official PURL types yet.

> How can I find details on these types in the future to troubleshoot issues like these?

This action uses the [Dependency Review API](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28) to fetch the dependency details. Calling this API will give you a `package_url` field for every one of your dependencies.

> Could the action log the full purl strings for each dependency when it runs so users like me can see the full details behind why a package is or isn't considered excluded?

I think it's reasonable to do this when we find errors/conflicts, I'd be happy help out with any questions you may have in case you want to submit a pull request.

I hope this clarifies your questions, if it doesn't please feel free to re-open this issue.
