### ISSUE TITLE
Clarify GitHub Enterprise Server support

### ISSUE THREAD

**Issue by rajbos** [actions/dependency-review-action#533]
It says in the readme [here](https://github.com/actions/dependency-review-action/blob/090b9fe2a1e5719958129542a80975806c13529a/README.md?plain=1#L41C1-L41C1) that this action is available in Enterprise Server starting with 3.6. We are runing 3.8.2 and the action is not synced onto the appliance by default. We do have GitHub connect enabled.

I've synced the action manually to another org on the same server for testing, and it works for incoming dependencies, including vulnerability scanning. 

It does not seem to be able to pick up the licenses for the packages though. Could this be because we have Artifactory in front of our 
npm setup? The `license` field stays empty:

![image](https://github.com/actions/dependency-review-action/assets/6085745/72e8576d-8805-484b-a0c4-511beaf914fd)

**Comment by febuiles** [comment]
@rajbos The [Dependency Review API](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28) does not return license information for packages in GHES, only vulnerabilities will be caught. This is something I've raised before and I hope there's a better Enterprise Server story in a few months. Closing this issue, please re-open if needed.

**Comment by febuiles** [comment]
@rajbos My understanding is that Dependency Review is not part of the Actions that are synced by default on GHES. We do have regular installation instructions [already in the README](https://github.com/actions/dependency-review-action#github-enterprise-server), but that document is very long and needs some love.

If you have specific suggestions on how to improve our existing instructions please open a PR or share your thoughts here and I'll get our docs updated!

**Comment by rajbos** [comment]
I've created #534 to clarify the language in the README with the missing parts that confused me initially.
