### ISSUE TITLE
Comment on PR Only if Failure

### ISSUE THREAD

**Issue by henry-prince-addepar** [actions/dependency-review-action#538]
It would be incredibly helpful and a better developer experience if you could add an option for `comment-summary-in-pr` that only comments `on-failure` and otherwise stays out of the way for passing checks. Thanks!

**Comment by febuiles** [comment]
@henry-prince-addepar that's a good idea! I don't have the bandwidth to implement this atm, but I'm leaving this open in case someone else is interested! If you want to submit a pull request I'd be happy to help, just ping me!
