### ISSUE TITLE
Option to Pass on Invalid SPDX License Definitions

### ISSUE THREAD

**Issue by henry-prince-addepar** [actions/dependency-review-action#539]
Currently, the PR check fails when packages "with invalid SPDX license definitions" are identified.

This is too draconian as we have `dependency-review-action` as a required check. Additional, license identification is not full proof enough to justify blocking a PR with this error.

Would it be possible to please add an option to still pass the check on this particular type of failure (but still fail on `deny-licenses`, of course)? Thank you!

**Comment by febuiles** [comment]
@henry-prince-addepar Can you post a log of the failures you've encountered? I'd be interested in understanding what's the issue with SPDX licenses before taking any action here.
