### ISSUE TITLE
Deny packages not allowing for version numbers

### ISSUE THREAD

**Issue by Killklli** [actions/dependency-review-action#546]
In the recent release the denied packages code is just doing a split on the package name so it only checks based off the package itself and not the version. 
We should have it account for versions and potentially a > check so we can do specific versions above the given one (I don't believe the purl spec defines that)

**Comment by febuiles** [comment]
@Killklli I like the proposal. We need to hash it out more explicitly. In principle I see two things here:

1. Add support for version numbers when blocking specific packages through `deny-package`. The scope here is very straightforward.
2. Add support for version comparisons (greater than, less than, etc.) on package version numbers. I feel this task is much greater in complexity: not all ecosystems use semantic versioning, and some manifest files don't specify a version number at all. For an example, see the `version` field in the following snippet:

```
$ gh api -H "Accept: application/vnd.github+json" repos/future-funk/refactored-chainsaw/dependency-graph/compare/ed6ace2b7a13ad8a80f1ae499436c256cf90ebf5...e99997ea27c964ddd84390e0a98a57a9e0afe706
[
  {
    "change_type": "added",
    "manifest": "Gemfile",
    "ecosystem": "rubygems",
    "name": "afterclass",
    "version": ">= 0",
    "package_url": "",
    "license": null,
    "source_repository_url": null,
    "scope": "runtime",
    "vulnerabilities": []
  },
```

If you want to write a PR for specific versions I'd be happy to help. For version comparisons I think the ask is much bigger and I'd need to read a more fleshed out version of how this would play along the existing code.

**Comment by febuiles** [comment]
Specific versions should be manageable now through the use of PURLs, closing this issue. Please re-open if needed.
