### ISSUE TITLE
Snapshots warnings for NPM projects

### ISSUE THREAD

**Issue by louis-bompart** [actions/dependency-review-action#566]
Hi there 👋 Since the release of v3.1.0, we noticed that the action is now reporting a warning about missing snapshots

I reckon NodeJS/NPM is one of the "statically defined dependencies in one of GitHub’s supported ecosystems", and thus do not need to submit those snapshots.

Am I missing something? What should we do to remove this warning from our JS projects?

**Comment by febuiles** [comment]
@louis-bompart Thanks for raising this issue. I've created #567 to keep track of general improvements we need to make to the new snapshots feature, and I'll update you here once we have improved the current situation.

**Comment by febuiles** [comment]
@louis-bompart closing this in favor of https://github.com/actions/dependency-review-action/issues/567, which contains more details and centralized another conversation. Your input would be appreciated.
