### ISSUE TITLE
Bug: Handling Rust/Cargo git dependencies

### ISSUE THREAD

**Issue by GeekMasher** [actions/dependency-review-action#602]
Today I noticed that when I changed my [Cargo.toml and updated the Cargo.lock for a git based dependency](https://github.com/advanced-security/codeql-extractor-iac/pull/100/files) that Dependency Review Action doesn't show any changes.

https://github.com/advanced-security/codeql-extractor-iac/pull/100#issuecomment-1786941812

The Action and PR Graph should show changes for git based dependencies.

**Dependency Graph:**

![Image](https://github.com/actions/dependency-review-action/assets/2772944/3b148baa-126e-435e-a89c-cde5590cdb33)

I don't know if this is just a Rust/Cargo issue or other ecosystems are affected by this too.

**Comment by febuiles** [comment]
@GeekMasher Thanks for raising this. [Dependency Review API](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28) does not support git-based dependencies. Closing!
