### ISSUE TITLE
Use with `scalacenter/sbt-dependency-submission` (Dependency Submission API)

### ISSUE THREAD

**Issue by MPV** [actions/dependency-review-action#608]
Hi,
I haven't gotten this action to work together with the Dependency Submission API — could you advise on how to do this?

Your docs describe that this should work, as per:
- https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
   >Note: The dependency review API and the dependency submission API work together. This means that the dependency review API will include dependencies submitted via the dependency submission API. This feature is currently in public beta and subject to change.

**Comment by MPV** [comment]
Here's an example of trying to get this to work together with `scalacenter/sbt-dependency-submission`:
- https://github.com/scalacenter/sbt-dependency-submission/issues/135

**Comment by febuiles** [comment]
Thanks for reporting this @MPV.

Taking a look at the sample repo, I see that the only existing snapshot is associated with the git revision `11ed13c5bba9814538dcbb244efc8af160291f37` (`HEAD` of `master`). 

The submission part of the CI run tells me that a new was snapshot generated: https://api.github.com/repos/MPV/github-dependency-review-for-scala/dependency-graph/snapshots/9003924, but I'm not sure where the SHA in there (`9d6c3624119eb3ab312b78cfa1149379447bc114`) is coming from.

Do you think maybe the force-push, or a failure in the snapshot submission could be related to this? Do you get the same behavior on a "clean" (no forces) PR? And if so, does the SHA of the resulting snapshot match your commits?

**Comment by MPV** [comment]
> Do you think maybe the force-push, or a failure in the snapshot submission could be related to this? Do you get the same behavior on a "clean" (no forces) PR? And if so, does the SHA of the resulting snapshot match your commits?

Sure, here is a PR with a fresh change, testing out your theory:
- https://github.com/MPV/github-dependency-review-for-scala/pull/4

**Comment by MPV** [comment]
Looks to me it’s using the `GITHUB_SHA`:
- https://github.com/search?q=repo%3Ascalacenter%2Fsbt-dependency-submission%20sha&type=code

Should it be using something like `github.event.pull_request.head.sha` instead (if called from a PR)?

As per:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

**Comment by MPV** [comment]
Seems similar to:
- https://github.com/actions/dependency-review-action/issues/545

**Comment by febuiles** [comment]
@juxtin would appreciate your input here.

**Comment by MPV** [comment]
We're drafting one way of fixing this over at:
- https://github.com/scalacenter/sbt-dependency-submission/pull/140

**Comment by febuiles** [comment]
@MPV that looks pretty very similar to @juxtin did to fix the Compose ecosystem, it looks like that should fix the problem of not being able to find the head SHA.

**Comment by juxtin** [comment]
Yeah, this is a very common issue for detectors that aren't using our toolkit. https://github.com/scalacenter/sbt-dependency-submission/pull/140 looks like it'll fix the problem 👍

**Comment by febuiles** [comment]
Reading through the comments, it looks like that fix did it! Closing this issue.
