### ISSUE TITLE
Mark previous PR comment as outdated

### ISSUE THREAD

**Issue by henriquevcosta** [actions/dependency-review-action#628]
I've had some instances in my repos where there was a dependency review comment highlighting a vulnerability but once I fix that issue and my build runs again (now without failing) the old comment is still there and visually polluting the conversation tab of the PR. 

Would it be possible for the action to hide its previous comment in the PR, marking it as outdated, so that it's still there but collapsed by default?

**Comment by febuiles** [comment]
@henriquevcosta updating outdated comments should work by default:


![Image](https://github.com/actions/dependency-review-action/assets/2161/cb3fee74-c9f3-416a-bccc-fc27a6a0f5a6)

Note the "`edited`" at the end of the comment header, it went from failing with some deps to green and updated the comment [in the PR](https://github.com/future-funk/cautious-telegram/pull/1) (you can tell the fixes by the CI status changes). 

Do you know any reproduction steps we could follow to try to reproduce?

**Comment by blaw2422** [comment]
@henriquevcosta  - i just fixed this by changing the workflow configuration to _always_ allow comments:

```diff
-          comment-summary-in-pr: on-failure
+          comment-summary-in-pr: always
```

**Comment by henriquevcosta** [comment]
@febuiles I'm sorry I've not commented on this for a while, I was away and I still haven't been able to allocate the time to reproduce this. Looking at the comment from blaw2422 and your example PR I'm guessing that the update will not be performed if I have `comment-summary-in-pr` property set to `on-failure` which has been the case, but I'd argue that it should update even in that scenario - at least my understanding of that property would be "if the build failed, create or update a comment. If the build succeeded, update a previous comment if it exists and if none exists then NOOP". 
Is that what's implemented? Would you agree?

**Comment by febuiles** [comment]
@henriquevcosta The comment behavior should be more consistent indeed! There's another open issue now regarding how comments work: https://github.com/actions/dependency-review-action/issues/647, will post a link to this issue there!
