### ISSUE TITLE
Update previous comment when failure is resolved

### ISSUE THREAD

**Issue by addepar-tg** [actions/dependency-review-action#647]
With the current behaviour of `comment-summary-in-pr` set to `on-failure`, a comment is made on failure and otherwise no comment is made.  This is an awesome UX and we are using it currently.

However, when the failure is resolved and the action succeeds, the failure comment is still present and therefore still looks relevant to the developer.  It would be great when `comment-summary-in-pr` is set to `on-failure`, any previous comment is marked as `Resolved` and therefore hidden from the developer.  If the action fails again, a new comment should be created.

Thank you.

**Comment by febuiles** [comment]
Another case of inconsistent comment behavior: https://github.com/actions/dependency-review-action/issues/628

**Comment by febuiles** [comment]
Thanks for the detailed feedback folks. We've been looking at ways to improve the experience with the comment/summary lately, and I think issue is something we can get sorted out soon. I don't have a timeframe to share, if you want to open a PR in the meantime I'd be happy to help.

/cc @jonjanego -- this is semi-related to the discussion and improvements you've been making in [starter-workflows](https://github.com/actions/starter-workflows/).

**Comment by jsoref** [comment]
- #941 was merged. The comment isn't resolved, but it is updated. See https://github.com/check-spelling-sandbox/fictional-garbanzo/pull/1#issuecomment-5546631376 for an example.

Note that I'm not remotely affiliated with this issue or this repository. I was just poking things for people.
