### ISSUE TITLE
Allow Running on PUSH events

### ISSUE THREAD

**Issue by ranma2913** [actions/dependency-review-action#677]
Hi, this is a great Action. I'd like to talk about updating it so it can work on a push event. 

Here's the use-case:

- User pushes code
- Code is scanned with dependency-review-action
- The check can then mark fail/pass based on the action configuration.

What I've tried:
- Run on a push but manually set the base-ref to something like prior tag matching a pattern or even first commit (`git rev-list --max-parents=0 HEAD`).  
      * It shows a warning about snapshots. 
![image](https://github.com/actions/dependency-review-action/assets/4295880/b3be9559-2113-451a-8d09-c683f955d308)
 
- These actually work, except the check is marked as failed with reason: `  Warning: Not in the context of a pull request. Skipping comment creation.` I realize this should be skipped on Push events, but why did it mark the run as fail?
      *  
![image](https://github.com/actions/dependency-review-action/assets/4295880/839053d6-f015-466e-9732-18db12377ef4)

**Comment by ranma2913** [comment]
As I'm looking more closely at the logs I notice there's actually an ERROR:

![image](https://github.com/actions/dependency-review-action/assets/4295880/65396932-f9fd-443b-94dd-dff695d2bafd)

**Comment by jonjanego** [comment]
@ranma2913 thanks for the suggestion!  Could you clarify a bit of what you're looking for the dependency review action to do by running it when you perform a push?

**Comment by juxtin** [comment]
@ranma2913 it looks like the action failed based on the license issues, rather than because of the non-PR warning. I'll go ahead and close this based on that assumption, but let us know if that's not the case.
