### ISSUE TITLE
Plugin management section is not taken into acount

### ISSUE THREAD

**Issue by laa** [actions/dependency-review-action#686]
We have recently added the spottles plugin and set up the plugin version only in the plugin management section.

Despite the fact that it is the most recent version of the plugin, action reports vulnerability that existed in the old version and has already been fixed.

if we add a version of the plugin in the plugin section of pom.xml, the review passes without problems.

**Comment by elireisman** [comment]
Hello, thanks for reporting this 🙇 

Can you provide more detail (specific repo, plugin/versions, example POM.xml etc.) and context for reproducing this?
