### ISSUE TITLE
Unable to use `allow-dependency-licenses` to allowlist Github Actions dependencies

### ISSUE THREAD

**Issue by magmanu** [actions/dependency-review-action#691]
Hi everyone 👋🏽 

One of the Github Actions in our workflow was flagged as containing a license our company doesn't normally allow, and we decided to allowlist it. 
However, I'm struggling to find a purl syntax that works to catch a GH Action. For example, `pkg:github/hashicorp/setup-terraform` is not valid to allowlist [this action](https://github.com/marketplace/actions/hashicorp-setup-terraform).

Could you please help?
Many thanks,
Manu

**Comment by febuiles** [comment]
@magmanu Using`pkg:githubactions/hashicorp/setup-terraform` should fix that until we have an official PURL for Actions. I'm closing this issue, but please re-open if the purl doesn't work.

**Comment by magmanu** [comment]
I confirm that works, thank you so much :)
