### ISSUE TITLE
Invalid SPDX License should (as opt-in?) be counted as warning

### ISSUE THREAD

**Issue by panthony** [actions/dependency-review-action#710]
Sometimes there are licenses that appears as "Invalid SPDX License" and "OTHER" as license:

![Capture d’écran 2024-03-13 à 07 48 38](https://github.com/actions/dependency-review-action/assets/230462/b1317ec1-d79d-4710-a912-8c91dd5e6c58)

If I export the SBOM from the dependency graph I have

```json
    {
      "SPDXID": "SPDXRef-maven-aopalliance-aopalliance-1.0",
      "name": "maven:aopalliance:aopalliance",
      "versionInfo": "1.0",
      "downloadLocation": "NOASSERTION",
      "filesAnalyzed": false,
      "supplier": "NOASSERTION",
      "externalRefs": [
        {
          "referenceCategory": "PACKAGE-MANAGER",
          "referenceLocator": "pkg:maven/aopalliance/aopalliance@1.0",
          "referenceType": "purl"
        }
      ]
    },
    {
      "SPDXID": "SPDXRef-maven-org.tukaani-xz-1.9",
      "name": "maven:org.tukaani:xz",
      "versionInfo": "1.9",
      "downloadLocation": "NOASSERTION",
      "filesAnalyzed": false,
      "supplier": "NOASSERTION",
      "externalRefs": [
        {
          "referenceCategory": "PACKAGE-MANAGER",
          "referenceLocator": "pkg:maven/org.tukaani/xz@1.9",
          "referenceType": "purl"
        }
      ]
    },
```

I think this should be counted as warning (perhaps can be toggled by a config?), same as "Unknown license", because in both cases it could not be determined automatically but that does not mean that the license is denied by the rules.

For ex, according to maven repository, both [aopalliance](https://mvnrepository.com/artifact/aopalliance/aopalliance) and [xz](https://mvnrepository.com/artifact/org.tukaani/xz) are public domain.

**Comment by febuiles** [comment]
@panthony thanks for the report 🙇 

The Action uses [ClearlyDefined](https://clearlydefined.io/) to fetch project licenses. I took a quick look at these two projects:

1. `aopalliance:aopalliance`: This was last updated in 2015, I could not find the `LICENSE` file in an online repo. ClearlyDefined reported [this as "OTHER" in this PR](https://github.com/clearlydefined/curated-data/pull/2599).

2. `org.tukaani/xz`: the ClearlyDefined license is [also OTHER](https://clearlydefined.io/definitions/maven/mavencentral/org.tukaani/xz/1.9). I took a look at [their repo](https://github.com/tukaani-project/xz-java/) and they are using a `0BSD` license, which I think should be renamed to `ISC` to be made SPDX-compliant (need a double check here).

For a quick fix, you can add an `allow-dependencies-licenses` option to your configuration, and add entries in PURL format. With that the Action should skip the licenses check.

For a long-term fix I'd encourage you to open a pull request in https://github.com/clearlydefined/curated-data/ to update the licenses for both of these projects in ClearlyDefined.

**Comment by panthony** [comment]
Thanks for you reply!

The downside of using "allow-dependencies-licenses" is that if the license changes between 2 versions I won't be notified, granted the chances of a library going from "0BSD" to "GPL-3.0" is low :)


Thanks for the pointer @ curated-data I did not know this project.
