### ISSUE TITLE
Bug: Some repos get error "fetch failed" when fetching v4.2.3

### ISSUE THREAD

**Issue by lindeberg** [actions/dependency-review-action#724]
We are getting error "fetch failed" when targeting the new version v4.2.3 for some of our repos.
Targeting v4.1.3 works fine. There was a similiar issue a while back: #609.
I see no difference in the repos except for the dependencies they have.
![image](https://github.com/actions/dependency-review-action/assets/15940340/b75fbaa7-372c-460a-8445-d2293250f058)

**Comment by febuiles** [comment]
@lindeberg thanks for the report again. I'm sorry to see y'all being affected by this, but I'm glad it seems like it's not related to the updated dependencies as we previously thought (I could still be wrong on this one 🤞).

Looking at the changelog between [4.1.3 and 4.2.3](https://github.com/actions/dependency-review-action/compare/v4.1.3...v4.2.3) the only changes I see in `package.json`/`package-lock.json` are:

* `eslint-plugin-jest` updated.
* `nodemon` updated.
* `@types/node` updated.

I could be wrong here, but I think all of those are used only in development. A couple of things that might help us here:

1. Can you add ` `show-openssf-scorecard: false` to your config and see if that makes a difference?
2. Can you give the Action `contents: write` permissions? (this shouldn't be required, I'm just wondering if something is at play here)

If none of these changes fixes the issue, I'll spin up a proxied self hosted runner on a cloud provider next week and try to reproduce.

**Comment by lindeberg** [comment]
@febuiles this is no longer a problem for us. Somehow after the weekend it's all good and green.👍

**Comment by febuiles** [comment]
Glad to hear this! Closing the issue. Please re-open if problems appear again.
