### ISSUE TITLE
Deny Packages Icon should be Red X (not a yellow warning)

### ISSUE THREAD

**Issue by austimkelly** [actions/dependency-review-action#731]
Split from: https://github.com/actions/dependency-review-action/issues/714

When a package is denied an error is created (as seen from the logs), but the icon is yellow in the PR annotation at "N package(s) deined":

![Screenshot 2024-03-26 at 8 04 00 AM](https://github.com/actions/dependency-review-action/assets/1355145/a22a388c-9e55-42c2-893e-ad3e301f8df2)

If the error can be raised in the **Denied** section of the logs that would be useful too:

![Screenshot 2024-03-26 at 8 06 51 AM](https://github.com/actions/dependency-review-action/assets/1355145/76f0334d-c046-4411-bf84-361c1de72db4)

**Comment by jonjanego** [comment]
Thank you for the feedback @austimkelly !

**Comment by jonjanego** [comment]
For denied packages we should use the error icon (red X).  For non-blocking informational / warning messages (in this case, packages with unknown licenses), we should use the yellow sign.

**Comment by jonjanego** [comment]
On 

https://github.com/actions/dependency-review-action/blob/2ce029c676cacb6112c47192ee072c7f783330c5/src/summary.ts#L72

Looks like this could be a quick change to:

`${checkOrFailIcon(deniedChanges.length)} ${`
