### ISSUE TITLE
Feature Request: Block on unknown licenses

### ISSUE THREAD

**Issue by austimkelly** [actions/dependency-review-action#732]
Split from: https://github.com/actions/dependency-review-action/issues/714

**Summary**: There's no way to block an unknown license. This would be ideal because you run the risk of introducing copy-left licenses. I'd love a simple flag that blocked on unknown licenses. Additionally, allow-licenses and deny-licenses cannot be used together which is expected behaviour, but there is otherwise no workaround.

**Recommendation**: Add a new flag with default of `false`: `fail-on-unknown-license`. 
Docs: When set to `true`, the action will fail on a pull request if 1 or more licenses have an unknown license. Use `allow-dependencies-licenses` to specify which packages to omit from the failure when `fail-on-unknown-license` is set to `true`.

**Comment by jonjanego** [comment]
Thank you @austimkelly.  We've already got similar feedback that we're tracking in https://github.com/actions/dependency-review-action/issues/672 so i'm going to close this issue as a duplicate in order to keep the issue board tidy.
