### ISSUE TITLE
Latest release breaks dependabot

### ISSUE THREAD

**Issue by phlax** [actions/dependency-review-action#757]
The latest release appears to have broken dependabot updates

Not sure exactly the cause but im guessing related to the upper case `V` in the release tag

**Comment by felickz** [comment]
FYI @juxtin

**Comment by juxtin** [comment]
Thanks @phlax, the uppercase `V` turned out to be the least of the issues with that release. I've just released `v4.3.1` to address some other bugs as well, that should take care of things.

**Comment by phlax** [comment]
thanks, confirming that latest release resolves the issue i was seeing
