### ISSUE TITLE
Error :- Purl String argument is required .

### ISSUE THREAD

**Issue by Shweta4398** [actions/dependency-review-action#763]
I am running the Dependency Review on one of my repo via Github Actions Repository . And I came across this error .

Can you please help me solving this ??

<img width="779" alt="Screenshot 2024-05-01 at 5 27 11 PM" src="https://github.com/actions/dependency-review-action/assets/106510489/ab72e2bf-3953-4185-94b6-e7df542b0c6f">

With regards,
Shweta Singh.

**Comment by jonjanego** [comment]
Hi @Shweta4398 could you please share the action configuration?

**Comment by juxtin** [comment]
Hi @Shweta4398, please update to v4.3.2 of the action. The hash you're using refers to v4.3.0, which has a couple of bugs with purls.

**Comment by juxtin** [comment]
@Shweta4398 sure, it's `0c155c5e8556a497adf53f2c18edabf945ed8e70`
