### ISSUE TITLE
[BUG] Incompatible licenses in actions/setup-python

### ISSUE THREAD

**Issue by mryzhov** [actions/dependency-review-action#842]
**Describe the bug**
The action report incompatible license issued when we tried to update the version of
actions/setup-python. It reports that MIT license is incompatible and lists the allowed licenses bellow, where MIT license exists:
https://github.com/openvinotoolkit/openvino_tokenizers/actions/runs/11514990374?pr=304 

**To Reproduce**
Please take a look at the PR - https://github.com/openvinotoolkit/openvino_tokenizers/pull/304

**Expected behavior**
The action should not report about incompatible licenses as they exists in the allowed licenses list.

**Screenshots**
![image](https://github.com/user-attachments/assets/b465e0e5-c7f8-48d2-970d-ca96026a408e)

**Action version**
a6993e2c61fd5dc440b409aa1d6904921c5e1894 # v4.3.5

**Examples**
Please take a look at the PR - https://github.com/openvinotoolkit/openvino_tokenizers/pull/304

**Comment by sergiuciudin** [comment]
Adding `BSD-2-Clause AND BSD-3-Clause` to the allowed list makes all the licenses fail

**Comment by mryzhov** [comment]
> Adding `BSD-2-Clause AND BSD-3-Clause` to the allowed list makes all the licenses fail. Seems the problem is in `AND` expression. According to the https://spdx.org/licenses/ it should work having only `BSD-2-Clause, BSD-3-Clause`

Thanks a lot, it helps.
